version: '3'

services:
  pgdb:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    hostname: ${DB_HOST}


  app:
    build: .
    command: python src/main.py
    restart: always
    env_file:
      - .env
    depends_on:
      - pgdb





