version: '3'

services:
  pgdb:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    hostname: ${DB_HOST}

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_COUNT_DB: ${REDIS_COUNT_DB}

  app:
    build: .
    command: python src/main.py
    restart: always
    env_file:
      - .env
    depends_on:
      - pgdb
      - redis
